---
- name: create users
  user:
    name: "{{ item.name }}"
    createhome: "{{ item.home }}"
    state: "{{ item.state }}"
    remove: "{{ item.remove }}"
    password: "{{ item.password | password_hash('sha512') }}"
  with_items: "{{ users }}"

- name: change hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: modify sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    backrefs: yes
    regexp: '^PasswordAuthentication no'
    line: 'PasswordAuthentication yes'
  notify:
    - restart sshd